### ISSUE TITLE
AttributeError: 'Upsample' object has no attribute 'recompute_scale_factor'

### ISSUE THREAD

**Issue by GZQ0723** [JakeVander/YOLOv5-Intrusion-Detection-System#1]
Download the latest tool and use version 5 of the pt model. Reasoning will lead to this problem
【AttributeError: 'Upsample' object has no attribute 'recompute_scale_factor'】

**Comment by jaycheney** [comment]
The version of some packages is incorrect. Please check the link https://blog.csdn.net/qq_40280673/article/details/125095353.
