### ISSUE TITLE
初始化失败

### ISSUE THREAD

**Issue by aodexiusi1997** [JakeVander/YOLOv5-Intrusion-Detection-System#2]
![image](https://github.com/jaycheney/YOLOv5-Intrusion-Detection-System/assets/145646451/8230a113-0f56-41a6-a873-a7a810405ed4)
作者您好，请问这种情况如何解决。基本已经尝试了网络上的办法。不知道你遇到过没有，请帮我看看，谢谢

**Comment by jaycheney** [comment]
> ![image](https://private-user-images.githubusercontent.com/145646451/346247848-8230a113-0f56-41a6-a873-a7a810405ed4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMjIxMzcsIm5iZiI6MTcyMTEyMTgzNywicGF0aCI6Ii8xNDU2NDY0NTEvMzQ2MjQ3ODQ4LTgyMzBhMTEzLTBmNTYtNDFhNi1hODczLWE3YTgxMDQwNWVkNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNlQwOTIzNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNDQ1MTE1OGIyZjRkZTk4YjdjOGY2MDAwNjRhZjRlNzdlNTgyYTIzMzg4YzAxYzkwZTY0N2I2ZWU4Mzk5Y2EzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wm9sDAONe4pfeFFua30XKIAGdixhTr8969rJCfQ7tRw) 作者您好，请问这种情况如何解决。基本已经尝试了网络上的办法。不知道你遇到过没有，请帮我看看，谢谢

看起来是PyQt5安装环境的问题，可以试着重新安装一下环境

**Comment by aodexiusi1997** [comment]
谢谢，但是试几次了，包括切换不同版本的qt5和opencv进行搭配，最后出现一个窗口，但是窗口中的汉字都显示不出来。难受！
